language: ruby
rvm:
  - 2.1
node_js:
  - stable
install: bundle install && npm install
script: ./bin/cibuild
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
