language: node_js
node_js:
  - 0.12.2
before_install:
  - rvm install 2.2.2
install: bundle install && npm install
script: ./bin/cibuild
cache:
  bundler: true
  directories:
    - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
