language: ruby
rvm:
  - 2.3.0
before_install:
  - nvm install 8.11.3
  - npm i -g npm@5
install:
  - bundle install
  - npm install
script:
  - npm run build-production
  - npm run test
cache:
  bundler: true
  directories:
    - node_modules
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
